### ISSUE TITLE
Line numbers for debug mode

### ISSUE THREAD

**Issue by gdevenyi** [kvz/bash3boilerplate#105]
Possible implementation here:
https://coderwall.com/p/wil8da/debug-bash-scripts-with-line-numbers-more-info

**Comment by virgilwashere** [comment]
Expanding upon #103, I've finished the code portion of adding colour and line numbers to debug mode.  

Incidentally, this PR also passes `shellcheck` linting on `main.sh` so that closes off #107.
All current tests are passing on 👷 `TravisCI`.

PR coming next, and then I plan to add ✅ tests to cover the expected output.

Will add another PR for updating `shellcheck` installation in `.travis.yml`

Virgil

**Comment by virgilwashere** [comment]
@kvz any idea what went wrong with the 🍏osx tests here: https://travis-ci.com/virgilwashere/bash3boilerplate/builds/117169882 ??

🐧linux passed!

This should be the extent of the changes...

```yaml
dist: xenial
addons:
 homebrew:
    update: true
    packages:
      - coreutils
      - gnu-sed
```

and the homebrew is just moving to `addons:` from `before_install:`
